### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by utkarshmani1997** [imfunniee/gitfolio#93]
<details>
<summary>System Information</summary>

| Name            | Value                                                          |
| --------------- | -------------------------------------------------------------- |
| OS              | Linux                                              |
| Node Version    | v12.11.0                           |
| Project Version | 5717f17 |

</details>

<details>
<summary>What is the current behavior?</summary>
While running `gitfolio ui` it returns /usr/bin/env: ‘node\r’: No such file or directory

</details>

<details>
<summary>What is the expected behavior?</summary>
It should run normally and start ui.

</details>

<details>
<summary>Logs</summary>

```

```

</details>

**Comment by Pliavi** [comment]
I'm having the same problem, for me, this error appears when i install Gitfolio with Yarn, but works when it is from NPM (as it needs sudo).


|Name             | Value    |
|-------------------|------------|
|OS                 | Linux     |
|Node Version | v12.9.1 |

**Comment by utkarshmani1997** [comment]
@Pliavi i have tried to install in both way but problem remains.

**Comment by Zephyr0402** [comment]
same issue here

**Comment by Pliavi** [comment]
I found the problem, all linebreaks are **CRLF** and the shell are interpreting the "carriage return"(`\r`) as part of the node name, it's happening because the project are using **CRLF** Unix systems can't recognize it well (so the problem my happen in MacOS too).

It would be fixed by using only **LF**, and setting in git to upload as it and not convert it back do **CRLF**, but I don't know if it will lead to windows problems... :confused: 

Another project that had the same problem: https://github.com/fastify/fastify/issues/1293 , looks like there will be no problem to convert, and will be good to set a .gitattribute file to handle it.
I tried change to LF and then it works, i'll make a PR

**Comment by coderjojo** [comment]
Still facing the same issue.

| Name            | Value                                                          |
| --------------- | -------------------------------------------------------------- |
| OS              | Linux                                              |
| Node Version    | v8.10.0  |

**Comment by coderjojo** [comment]
> Still facing the same issue.
> Name 	Value
> OS 	Linux
> Node Version 	v8.10.0

Resolved after updating node.
